name: Build and Deploy to GKE

on:
  push:
    branches:
      - stedi_main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1 # Add your cluster name here.
  GKE_ZONE: us-central1 # Add your cluster zone here.
  DEPLOYMENT_NAME: pius-api # Add your deployment name here.
  IMAGE: pius-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment:
      name: development
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker us-docker.pkg.dev

      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Build
        run: |-
          docker build \
            --tag "us-docker.pkg.dev/my-devops-team-404512/pius-api/stedi-api:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Publish
        run: |-
          docker push "us-docker.pkg.dev/my-devops-team-404512/pius-api/stedi-api:latest"

      - name: Deploy
        run: |-
          kubectl apply -f prod-manifest.yaml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
